### ISSUE TITLE
Please update Dockerfile

### ISSUE THREAD

**Issue by ad-on-is** [aacebedo/dnsdock#122]
I tried to pull the image, and I'm getting the following error:

Using default tag: latest
latest: Pulling from conz27/dnsdock
Docker Image Format v1 and Docker Image manifest version 2, schema 1 support has been removed. Suggest the author of docker.io/conz27/dnsdock:latest to upgrade the image to the OCI Format or Docker Image manifest v2, schema 2. More information at https://docs.docker.com/go/deprecated-image-specs/

**Comment by aacebedo** [comment]
Ok I'll have a look

**Comment by ad-on-is** [comment]
This tool turned out to be great. However, I had to do some changes, to make it work as I acutally expect it to do.
https://github.com/ad-on-is/dnsdock

Maybe you're interested in some of the changes and can cherry-pick them, if you like.

- Dockerfile fixed - using alpine instead of scratch
- added SRV records
- added multiple A-records, with the possibility to filter by prefix... i.e. --ipPrefix 192... also, if a local machine is from the same LAN, it won't show other IPs.


edit: Sorry, I accidentally closed the issue ... my bad!

**Comment by aacebedo** [comment]
No problem, I reopened the issue.

Improvements are very welcomed. Could you create PR ?

A question about dockerfile, why would you use alpine instead of scratch ? The binary does not need any files from an OS so what does it bring ?

**Comment by aacebedo** [comment]
By the way, I pulled the latest version (`docker pull aacebedo/dnsdock:latest-amd64`) without issue. Are you using the correct ref ?

**Comment by ad-on-is** [comment]
I was to lazy to dig into the problem on how to use scratch properly, since I'm working on my docker setup, and needed the image assap :-D

I just did a `docker pull aacebedo/dnsdock:lates`t

**Comment by ad-on-is** [comment]
Yeah... I might do some PRs in the future, when time allows it. I'd need to cherry-pick, though, since I've implemented some things that I need, but would probably be out of scope for this particular project, or maybe not.

I also fixed some error-handling, where dnsdock would stop processing containers, when an (imho) irrelevant error occurs, like when a service has no IP assigned to it (which often happens on services that have `network_mode=host`

**Comment by aacebedo** [comment]
latest is not applicable anymore as it does not handle arch. I will remove it to avoid such error for the future.
For scratch I still don't see the iinterest in using alpine so I would keep it.

Other modifications seem great so if you are ok to make the PR I'll be happy to merge it (please make commit message compatible with commitizen)

**Comment by ad-on-is** [comment]
Yeah, sure. I'm fine with scratch. Using alpine was just a quickfix, you can ignore it.

Will cherry-pick everything and do a propper PR
